// Validates the per-language files and builds everything that consumes them.
//   node scripts/i18n-build.cjs
// Inputs : translations/design/en.json (source) and translations/design/<lang>.json ({ "English source": "translation" })
// Outputs: src/i18n/design-dict.ts            (what the dashboards load)
//          translations/design/design.csv      (one row per string, one column per language)
//          translations/design/engine-import.json (rows shaped for the main translation engine)
const fs = require('fs');
const path = require('path');
const DIR = path.join(__dirname, '../translations/design');
const LANGS = { fr: 'Français', pcm: 'Naijá Pidgin', yo: 'Yorùbá', ha: 'Hausa', ig: 'Igbo' };
const en = JSON.parse(fs.readFileSync(path.join(DIR, 'en.json'), 'utf8'));
const ph = (s) => (s.match(/\{\w+\}/g) || []).sort().join(',');
let problems = 0;
const dict = {};
for (const code of Object.keys(LANGS)) {
  const file = path.join(DIR, `${code}.json`);
  const t = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {};
  dict[code] = {};
  let missing = 0;
  for (const { key } of en) {
    const v = t[key];
    if (typeof v !== 'string' || !v.trim()) { missing++; continue; }
    if (ph(v) !== ph(key)) { console.log(`PLACEHOLDER ${code}: ${JSON.stringify(key)} -> ${JSON.stringify(v)}`); problems++; continue; }
    dict[code][key] = v;
  }
  const extra = Object.keys(t).filter((k) => !en.some((e) => e.key === k));
  console.log(`${code}: ${Object.keys(dict[code]).length}/${en.length} translated, ${missing} missing, ${extra.length} unknown keys`);
  problems += missing + extra.length;
}
const q = (s) => JSON.stringify(s);
let ts = '// Generated by scripts/i18n-build.cjs from translations/design/*.json. Do not edit by hand.\n';
ts += 'export const DESIGN_DICT: Record<string, Record<string, string>> = {\n';
for (const code of Object.keys(LANGS)) {
  ts += `  ${code}: {\n`;
  for (const { key } of en) if (dict[code][key] !== undefined) ts += `    ${q(key)}: ${q(dict[code][key])},\n`;
  ts += '  },\n';
}
ts += '};\n';
fs.writeFileSync(path.join(__dirname, '../src/i18n/design-dict.ts'), ts);

const csv = (s) => `"${String(s).replace(/"/g, '""')}"`;
let rows = ['key,' + Object.keys(LANGS).join(',') + ',used_in'];
for (const { key, where } of en) rows.push([csv(key), ...Object.keys(LANGS).map((c) => csv(dict[c][key] ?? '')), csv(where.join(' '))].join(','));
fs.writeFileSync(path.join(DIR, 'design.csv'), rows.join('\n') + '\n');

const imp = [];
for (const { key, where } of en) for (const code of Object.keys(LANGS)) if (dict[code][key] !== undefined) imp.push({ namespace: 'legacy-inline', source: key, language: code, value: dict[code][key], status: 'ai_translated', context: where[0] });
fs.writeFileSync(path.join(DIR, 'engine-import.json'), JSON.stringify(imp, null, 1) + '\n');
console.log(problems ? `${problems} problem(s)` : 'ok');
